language: go
os:
- linux
- osx
go:
- 1.6.2
env:
  global:
  - secure: SltOvsVGWeiK3b5NRUdh1vqmiwAELvEKlnNHyAA2iWO5TJBFU7noSwb5Q8bB0yTtVGZCcapX4hqTwn9qxBIWBp8RpNGH884wyv1YTfm1LXSX7hLFjHMPYRKtWWTXMvUBMUSHqUx5bgvlZh6JZz1fOXPSi0alROMCZb9iE5Ewxr4M16u3vnh1sbgiHG76M0s69q+v49k/LADN9l02n5OjHRJSsSVKWJRTlKDS6CdpPJWq6T2P7lKxWlPUd4Jq1UhFY6g88YbDGUyjrUeTtx6ynUgspkTsGKPOv+TBeS710tW4eoJ6YnGdJX/yuzilMnSfWllU/5dDvYgFGx7BVxPKvgQCfsof706KJkl/Iq4ksewX8SXz6wKSyZhED2B6fIA4m7m+cs8neZdYH6KXZS2gJp96/7Us3j5JnCaKAbZWuT4OD0PGDqS81BpHRH5JcryZrCUeQqEK6uc/7XU+0tPc3BiNpCm4xffhCysygPrJ9aMzfhiXDW1s0C5/Eec9g7Pdw2n7GlTlQyD/fzI4B/af+FH7RHTr0aMK5DRKpZ8A2qMa53Ps+cPU4mRYNVRnuuM+Bue5P2GJTHdsGAg55A50b93B+r0jy5Rl/uuBfmjqz2WGcw4n7J6IkGVlZKCrrlaznqa3jHDtPGW3c+krW+mnTy8K/hdbaZ0xLBVCwJgttfQ=
  - secure: NIy7DxZyPIIWQYhf1DvMElQD3x+uxMU5Jlyh/vXXIbW4HJrpUe8M1pyVEpHRVj0tzk9DGt0voSF75LMrpVPcvgKwQ5ohmAunqWak3ARGi9kva+nQ4m77r3Yp9gg90rs2OWnCr2VuwYEdoVEFhp02HW1+2KsbntPhjG8zTKUKpqfq9d6PNMnqWc1fw42CiQPKnSHEYSa6r5QssPs56nYTqevGRzZMKrCNnhmp2kIrWsuyZS7M4aWNaYeXcwtjQJsLo7vR+xlDh3Iz7oFRXhYcGmPdj+x1m9YRipGCaTzG7jNY1lmoF+y6HT9NNgyryvl5GPY80v/fZJEtuk0qQbk9nfjrR5VOcLVCWVJIwWZOr0d9z4oWbn8JSEEtV18tdxZ4uvVuYekYWv5+OTSpKfGRSGLsCIgwGqe3PF915/vwC3+ShOeTrS/UIcEl9+WeQQC0ohrZhpOFB3Q82Ub9Pm8o2hGI0nmT0BmWw0JEItV9Zrjfnch37ILeuQ4gVX2bU1dfEl068QGsuGlL9hiI8veqqMzWVES3DoxVn6TkhNJoHFw2V1t1ujw0IOUmrQbKcmn9TtqBkdiKpsglS48/MVJeNN8wVF/nQDx75M9QnCbZ0UitgO7JBsrMlC/nYFv3m5Jw5AD9GmeFy96Qfpw9fhgZx+gkI3La4VhiEUMPpe/khG8=
install:
  - go get golang.org/x/net/websocket
  - go get github.com/pkg/errors
  - go get github.com/getblank/uuid
  - go get github.com/Sirupsen/logrus
  - go get github.com/getblank/wango
  - go get github.com/getblank/rgx
  - go get github.com/labstack/echo
  - go get github.com/labstack/echo/engine/standard
  - go get github.com/labstack/echo/middleware
  - go get github.com/spf13/cobra
script: go get -t -v ./...
after_success:
- curl --ftp-create-dirs --data-binary -k -T $HOME/gopath/bin/blank-router -u $FTP_USER:$FTP_PASSWORD ftp://releases.getblank.net/releases/blank-router/$(date +%Y-%m-%d_%H:%M)-$TRAVIS_OS_NAME/blank-router
- curl --ftp-create-dirs --data-binary -k -T $HOME/gopath/bin/blank-router -u $FTP_USER:$FTP_PASSWORD ftp://releases.getblank.net/releases/blank-router/$TRAVIS_OS_NAME/blank-router