language: go
os:
  - linux
go:
  - 1.6.2
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq upx
  - go get -u golang.org/x/net/websocket
  - go get -u github.com/pkg/errors
  - go get -u github.com/getblank/uuid
  - go get -u github.com/Sirupsen/logrus
  - go get -u github.com/getblank/wango
  - go get -u github.com/getblank/rgx
  - go get -u github.com/labstack/echo
  - go get -u github.com/labstack/echo/engine/standard
  - go get -u github.com/labstack/echo/middleware
  - go get -u github.com/spf13/cobra
script:
  - go get -t -v ./...
after_success:
  - go build -ldflags "-X main.buildTime=`date +%Y-%m-%d:%H:%M:%S` -X main.gitHash=`git rev-parse --short HEAD`"
  - upx --best blank-router
  - curl --ftp-create-dirs --data-binary -k -T ./blank-router -u $FTP_USER:$FTP_PASSWORD ftp://releases.getblank.net/releases/blank-router/$(date +%Y-%m-%d_%H:%M)-linux/blank-router
  - curl --ftp-create-dirs --data-binary -k -T ./blank-router -u $FTP_USER:$FTP_PASSWORD ftp://releases.getblank.net/releases/blank-router/linux/blank-router

  - GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.buildTime=`date +%Y-%m-%d:%H:%M:%S` -X main.gitHash=`git rev-parse --short HEAD`"
  - upx --best blank-router
  - curl --ftp-create-dirs --data-binary -k -T ./blank-router -u $FTP_USER:$FTP_PASSWORD ftp://releases.getblank.net/releases/blank-router/$(date +%Y-%m-%d_%H:%M)-osx/blank-router
  - curl --ftp-create-dirs --data-binary -k -T ./blank-router -u $FTP_USER:$FTP_PASSWORD ftp://releases.getblank.net/releases/blank-router/osx/blank-router
